@baseUrl = http://localhost:4000
@authAccessToken = Authorization: Bearer {{authLogin.response.body.$.accessToken}}
@contentType = Content-Type: application/json

Get {{baseUrl}}

###

# @name authLogin
POST {{baseUrl}}/auth/login
{{contentType}}

{
    "username": "Gino",
    "password": "123456"
}

###
POST {{baseUrl}}/auth/register
{{contentType}}

{
    "username": "Ginoa",
    "password": "123456",
    "email": "thatishayanona@hotmail.com",
    "name": "thatishayanon",
    "surname": "Witthayawathanon"
    
}
###

GET {{baseUrl}}/users/profile
{{authAccessToken}}


###
POST  {{baseUrl}}/auth/refresh-token
{{authAccessToken}}

###
#############################################################3
### Articles
POST {{baseUrl}}/articles
{{contentType}}
{{authAccessToken}}

{
    "title": "Test 8",
    "description": "more Detail8"
}

###
GET {{baseUrl}}/articles
{{contentType}}
{{authAccessToken}}

###
GET {{baseUrl}}/articles/62cf44332b52727cba9693a4
{{contentType}}
{{authAccessToken}}

###
PATCH {{baseUrl}}/articles/id
{{contentType}}
{{authAccessToken}}

{}

###
DELETE {{baseUrl}}/articles/62cf48de8e25a31401ccc433
{{contentType}}
{{authAccessToken}}












